# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
#ZSH_THEME="robbyrussell"
ZSH_THEME="muse"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable bi-weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment to change how often before auto-updates occur? (in days)
# export UPDATE_ZSH_DAYS=13

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want to disable command autocorrection
# DISABLE_CORRECTION="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
#plugins=(git rvm gem)
plugins=(cargo rust)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...

# Maybe I should switch this to a switch in $TERM and then do things inside?
# If not running interactively, do not do anything
[[ $- != *i* ]] && return
[[ -z "$TMUX" && $TERM = *termite ]] && exec tmux

# If we have .cargo it means that we are working with rust
# As I won't add anything to .profile we have to source the env
# variables ourselves
[[ -d ~/.cargo ]] && source ~/.cargo/env
[[ -d ~/.cargo ]] && export RUST_SRC_PATH=~/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src


alias kvm="qemu-system-x86_64 -enable-kvm -cpu host"
alias wine="FREETYPE_PROPERTIES=\"truetype:interpreter-version=35\" wine"

alias wine32="FREETYPE_PROPERTIES=\"truetype:interpreter-version=35\" WINEARCH=win32 WINEPREFIX=~/.wine32 wine"
alias winecfg32="FREETYPE_PROPERTIES=\"truetype:interpreter-version=35\" WINEARCH=win32 WINEPREFIX=~/.wine32 winecfg"
alias winetricks32="FREETYPE_PROPERTIES=\"truetype:interpreter-version=35\" WINEARCH=win32 WINEPREFIX=~/.wine32 winetricks"
alias regedit32="FREETYPE_PROPERTIES=\"truetype:interpreter-version=35\" WINEARCH=win32 WINEPREFIX=~/.wine32 regedit"

export EDITOR=vim

zstyle ':completion:*:*:vim:*:*files' ignored-patterns '*.o' '*.lo'
